<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>BetterJunimos</AssemblyName>
    <RootNamespace>BetterJunimos</RootNamespace>
    <Version>3.2.0</Version>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net6.0</TargetFramework>
    <EnableHarmony>true</EnableHarmony>
  </PropertyGroup>

  <ItemGroup>
    <!-- bundle the Content Patcher pack with the mod, so it ends up in the release zip -->
    <ContentPacks Include="[CP] Better Junimos Config Wizard" Version="$(Version)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
    <PackageReference Include="System.ValueTuple" Version="4.6.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>
